name: Build macOS VM (PR)

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY_HOST: registry.local
  REGISTRY_PORT: 5000
  REGISTRY_IMAGE: sequoia-tester
  TART_INSECURE: "--insecure"
  BUILD_TAG: pr-${{ github.event.pull_request.number }}-${{ github.sha }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew tap cirruslabs/cli || true
          brew install packer cirruslabs/cli/tart ansible || true

      - name: Run macOS VM build
        working-directory: mac/tester15
        env:
          VM_NAME: sequoia-tester
          VAULT_FILE:  ${{ github.workspace }}/mac/tester15/vault-fake.yaml
        run: |
          echo "Using VAULT_FILE=$VAULT_FILE"
          chmod +x builder.sh
          ./builder.sh

      - name: Push built VM to local OCI registry
        if: ${{ success() }}
        env:
          REGISTRY: ${{ env.REGISTRY_HOST }}:${{ env.REGISTRY_PORT }}
          IMAGE: ${{ env.REGISTRY_IMAGE }}
          TAG: ${{ env.BUILD_TAG }}
        run: |
          echo "Pushing ${IMAGE}:${TAG} to ${REGISTRY} ..."
          tart push $TART_INSECURE ${IMAGE} ${REGISTRY}/${IMAGE}:${TAG}

      - name: Tag and push PR-latest alias
        if: ${{ success() }}
        env:
          REGISTRY: ${{ env.REGISTRY_HOST }}:${{ env.REGISTRY_PORT }}
          IMAGE: ${{ env.REGISTRY_IMAGE }}
        run: |
          PR_TAG="pr-${{ github.event.pull_request.number }}-latest"
          echo "Pushing ${IMAGE}:${PR_TAG} to ${REGISTRY} ..."
          tart push $TART_INSECURE ${IMAGE} ${REGISTRY}/${IMAGE}:${PR_TAG}